# Generated by Django 5.2.7 on 2025-10-03 12:40

import django.core.validators
import django.db.models.deletion
import encrypted_model_fields.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_token', models.CharField(max_length=255, unique=True)),
                ('device_info', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('target_samples', models.PositiveIntegerField(default=5)),
                ('completed_samples', models.PositiveIntegerField(default=0)),
                ('average_quality', models.FloatField(default=0.0)),
                ('min_quality_threshold', models.FloatField(default=0.7)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('session_log', models.JSONField(default=list)),
                ('error_messages', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Enrollment Session',
                'verbose_name_plural': 'Enrollment Sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='FaceEmbedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('embedding_vector', encrypted_model_fields.fields.EncryptedTextField()),
                ('embedding_hash', models.CharField(max_length=64, unique=True)),
                ('quality_score', models.FloatField(help_text='Quality score of the face capture (0-1)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('confidence_score', models.FloatField(help_text='Detection confidence score (0-1)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('face_bbox', models.JSONField(help_text='Face bounding box coordinates [x1, y1, x2, y2]')),
                ('face_landmarks', models.JSONField(blank=True, help_text='Facial landmarks coordinates', null=True)),
                ('sample_number', models.PositiveIntegerField()),
                ('face_image', models.ImageField(blank=True, help_text='Cropped face image (encrypted storage)', null=True, upload_to='faces/%Y/%m/%d/')),
                ('liveness_score', models.FloatField(default=0.0, help_text='Liveness detection score', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('anti_spoofing_score', models.FloatField(default=0.0, help_text='Anti-spoofing detection score', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('capture_device', models.CharField(blank=True, max_length=100)),
                ('capture_resolution', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='recognition.enrollmentsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_embeddings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Face Embedding',
                'verbose_name_plural': 'Face Embeddings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuthenticationAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device_fingerprint', models.CharField(blank=True, max_length=255)),
                ('submitted_embedding', encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True)),
                ('similarity_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('liveness_score', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('quality_score', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('obstacles_detected', models.JSONField(default=list)),
                ('result', models.CharField(choices=[('success', 'Success'), ('failed_similarity', 'Failed - Low Similarity'), ('failed_liveness', 'Failed - Liveness Check'), ('failed_quality', 'Failed - Poor Quality'), ('failed_obstacles', 'Failed - Obstacles Detected'), ('failed_multiple_faces', 'Failed - Multiple Faces'), ('failed_no_face', 'Failed - No Face Detected'), ('failed_system_error', 'Failed - System Error')], max_length=30)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('face_bbox', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auth_attempts', to=settings.AUTH_USER_MODEL)),
                ('matched_embedding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_matches', to='recognition.faceembedding')),
            ],
            options={
                'verbose_name': 'Authentication Attempt',
                'verbose_name_plural': 'Authentication Attempts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FaceRecognitionModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=50)),
                ('model_type', models.CharField(choices=[('detection', 'Face Detection'), ('recognition', 'Face Recognition'), ('liveness', 'Liveness Detection'), ('anti_spoofing', 'Anti-Spoofing')], max_length=20)),
                ('configuration', models.JSONField(default=dict)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('precision', models.FloatField(blank=True, null=True)),
                ('recall', models.FloatField(blank=True, null=True)),
                ('f1_score', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_models', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Face Recognition Model',
                'verbose_name_plural': 'Face Recognition Models',
            },
        ),
        migrations.CreateModel(
            name='LivenessDetection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('blinks_detected', models.PositiveIntegerField(default=0)),
                ('blink_quality_scores', models.JSONField(default=list)),
                ('ear_history', models.JSONField(default=list)),
                ('ear_baseline', models.FloatField(blank=True, null=True)),
                ('frames_processed', models.PositiveIntegerField(default=0)),
                ('valid_frames', models.PositiveIntegerField(default=0)),
                ('challenge_type', models.CharField(choices=[('blink', 'Blink Detection'), ('head_turn', 'Head Movement'), ('smile', 'Smile Detection'), ('random', 'Random Challenge')], default='blink', max_length=20)),
                ('challenge_completed', models.BooleanField(default=False)),
                ('liveness_score', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('is_live', models.BooleanField(default=False)),
                ('debug_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('authentication_attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='liveness_detection', to='recognition.authenticationattempt')),
            ],
            options={
                'verbose_name': 'Liveness Detection',
                'verbose_name_plural': 'Liveness Detections',
            },
        ),
        migrations.CreateModel(
            name='ObstacleDetection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('glasses_detected', models.BooleanField(default=False)),
                ('glasses_confidence', models.FloatField(default=0.0)),
                ('mask_detected', models.BooleanField(default=False)),
                ('mask_confidence', models.FloatField(default=0.0)),
                ('hat_detected', models.BooleanField(default=False)),
                ('hat_confidence', models.FloatField(default=0.0)),
                ('hand_covering', models.BooleanField(default=False)),
                ('hand_confidence', models.FloatField(default=0.0)),
                ('has_obstacles', models.BooleanField(default=False)),
                ('obstacle_score', models.FloatField(default=0.0)),
                ('detection_details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('authentication_attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='obstacle_detection', to='recognition.authenticationattempt')),
            ],
            options={
                'verbose_name': 'Obstacle Detection',
                'verbose_name_plural': 'Obstacle Detections',
            },
        ),
        migrations.AddIndex(
            model_name='enrollmentsession',
            index=models.Index(fields=['user', 'status'], name='recognition_user_id_c08a4b_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollmentsession',
            index=models.Index(fields=['session_token'], name='recognition_session_5b7935_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollmentsession',
            index=models.Index(fields=['started_at'], name='recognition_started_e63576_idx'),
        ),
        migrations.AddIndex(
            model_name='faceembedding',
            index=models.Index(fields=['user', 'is_active'], name='recognition_user_id_dd20a7_idx'),
        ),
        migrations.AddIndex(
            model_name='faceembedding',
            index=models.Index(fields=['embedding_hash'], name='recognition_embeddi_c99014_idx'),
        ),
        migrations.AddIndex(
            model_name='faceembedding',
            index=models.Index(fields=['quality_score'], name='recognition_quality_5ecf5e_idx'),
        ),
        migrations.AddIndex(
            model_name='faceembedding',
            index=models.Index(fields=['created_at'], name='recognition_created_dccb94_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='faceembedding',
            unique_together={('enrollment_session', 'sample_number')},
        ),
        migrations.AddIndex(
            model_name='authenticationattempt',
            index=models.Index(fields=['user', 'created_at'], name='recognition_user_id_3c58fd_idx'),
        ),
        migrations.AddIndex(
            model_name='authenticationattempt',
            index=models.Index(fields=['session_id'], name='recognition_session_fb8c83_idx'),
        ),
        migrations.AddIndex(
            model_name='authenticationattempt',
            index=models.Index(fields=['result', 'created_at'], name='recognition_result_c5d85b_idx'),
        ),
        migrations.AddIndex(
            model_name='authenticationattempt',
            index=models.Index(fields=['ip_address', 'created_at'], name='recognition_ip_addr_46f831_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='facerecognitionmodel',
            unique_together={('name', 'version')},
        ),
    ]
