# Generated by Django 5.2.7 on 2025-10-09 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('recognition', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='authenticationattempt',
            name='recognition_user_id_3c58fd_idx',
        ),
        migrations.RemoveIndex(
            model_name='enrollmentsession',
            name='recognition_user_id_c08a4b_idx',
        ),
        migrations.RemoveIndex(
            model_name='faceembedding',
            name='recognition_user_id_dd20a7_idx',
        ),
        migrations.RemoveField(
            model_name='authenticationattempt',
            name='user',
        ),
        migrations.RemoveField(
            model_name='enrollmentsession',
            name='user',
        ),
        migrations.RemoveField(
            model_name='faceembedding',
            name='user',
        ),
        migrations.RemoveField(
            model_name='facerecognitionmodel',
            name='created_by',
        ),
        migrations.AddField(
            model_name='authenticationattempt',
            name='client_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legacy_auth_attempts', to='clients.clientuser'),
        ),
        migrations.AddField(
            model_name='enrollmentsession',
            name='client_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legacy_enrollment_sessions', to='clients.clientuser'),
        ),
        migrations.AddField(
            model_name='faceembedding',
            name='client_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legacy_embeddings', to='clients.clientuser'),
        ),
        migrations.AddField(
            model_name='facerecognitionmodel',
            name='created_by_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_models', to='clients.client'),
        ),
        migrations.AddIndex(
            model_name='authenticationattempt',
            index=models.Index(fields=['client_user', 'created_at'], name='recognition_client__26ffc7_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollmentsession',
            index=models.Index(fields=['client_user', 'status'], name='recognition_client__4f2d04_idx'),
        ),
        migrations.AddIndex(
            model_name='faceembedding',
            index=models.Index(fields=['client_user', 'is_active'], name='recognition_client__3f5581_idx'),
        ),
    ]
