# Generated by Django 5.2.7 on 2025-10-09 12:42

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import encrypted_model_fields.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('domain', models.URLField(help_text='Primary domain for CORS and webhook validation')),
                ('api_key', encrypted_model_fields.fields.EncryptedCharField(db_index=True, unique=True)),
                ('secret_key', encrypted_model_fields.fields.EncryptedTextField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('inactive', 'Inactive'), ('trial', 'Trial')], default='trial', max_length=20)),
                ('tier', models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], default='basic', max_length=20)),
                ('webhook_url', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('webhook_secret', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('allowed_domains', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, help_text='Allowed domains for CORS', size=None)),
                ('rate_limit_per_hour', models.PositiveIntegerField(default=1000)),
                ('rate_limit_per_day', models.PositiveIntegerField(default=10000)),
                ('features', models.JSONField(default=dict, help_text='Feature configuration: enrollment, recognition, liveness, etc.')),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client_id'], name='clients_cli_client__a44f5d_idx'), models.Index(fields=['api_key'], name='clients_cli_api_key_b3cbe8_idx'), models.Index(fields=['status'], name='clients_cli_status_ce0d15_idx'), models.Index(fields=['tier'], name='clients_cli_tier_b5358a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClientAPIUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('endpoint', models.CharField(choices=[('enrollment', 'Enrollment'), ('recognition', 'Recognition'), ('liveness', 'Liveness Detection'), ('webhook', 'Webhook'), ('analytics', 'Analytics')], max_length=50)),
                ('method', models.CharField(max_length=10)),
                ('status_code', models.IntegerField()),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('response_time_ms', models.FloatField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_usage', to='clients.client')),
            ],
            options={
                'verbose_name': 'API Usage',
                'verbose_name_plural': 'API Usage',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', 'created_at'], name='clients_cli_client__c6456c_idx'), models.Index(fields=['endpoint', 'created_at'], name='clients_cli_endpoin_9169d2_idx'), models.Index(fields=['status_code'], name='clients_cli_status__26f854_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClientUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_user_id', models.CharField(db_index=True, max_length=100)),
                ('external_user_uuid', models.UUIDField(blank=True, db_index=True, null=True)),
                ('profile', models.JSONField(default=dict, help_text='User profile from client system')),
                ('is_enrolled', models.BooleanField(default=False)),
                ('enrollment_completed_at', models.DateTimeField(blank=True, null=True)),
                ('face_auth_enabled', models.BooleanField(default=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_recognition_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='clients.client')),
            ],
            options={
                'verbose_name': 'Client User',
                'verbose_name_plural': 'Client Users',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', 'external_user_id'], name='clients_cli_client__11e50a_idx'), models.Index(fields=['external_user_uuid'], name='clients_cli_externa_05797f_idx'), models.Index(fields=['is_enrolled'], name='clients_cli_is_enro_29589e_idx')],
                'unique_together': {('client', 'external_user_id')},
            },
        ),
        migrations.CreateModel(
            name='ClientWebhookLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('retrying', 'Retrying')], default='pending', max_length=20)),
                ('response_status_code', models.IntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_logs', to='clients.client')),
            ],
            options={
                'verbose_name': 'Webhook Log',
                'verbose_name_plural': 'Webhook Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', 'event_type'], name='clients_cli_client__5d8ea3_idx'), models.Index(fields=['status', 'next_retry_at'], name='clients_cli_status_377689_idx'), models.Index(fields=['created_at'], name='clients_cli_created_8c770e_idx')],
            },
        ),
    ]
