# Generated by Django 5.2.7 on 2025-10-09 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuser',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='User profile image from enrollment', null=True, upload_to='client_users/profiles/%Y/%m/%d/'),
        ),
    ]
