# Generated by Django 5.2.7 on 2026-01-06 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_add_profile_image_to_clientuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuser',
            name='old_profile_photo',
            field=models.ImageField(blank=True, help_text='Previous profile photo for similarity comparison', null=True, upload_to='client_users/old_profiles/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='clientuser',
            name='similarity_with_old_photo',
            field=models.FloatField(blank=True, help_text='Similarity score between current and old profile photo (0.0 - 1.0)', null=True),
        ),
    ]
