# Generated by Django 5.2.7 on 2026-01-06 08:46

import clients.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_clientuser_old_profile_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientuser',
            name='old_profile_photo',
            field=models.ImageField(blank=True, help_text='Previous profile photo for similarity comparison', null=True, storage=clients.models.get_media_storage, upload_to='client_users/old_profiles/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='clientuser',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='User profile image from enrollment', null=True, storage=clients.models.get_media_storage, upload_to='client_users/profiles/%Y/%m/%d/'),
        ),
    ]
