# Generated by Django 5.2.7 on 2026-01-12 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_clientuser_old_profile_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuser',
            name='cached_embedding',
            field=models.BinaryField(blank=True, help_text='Cached face embedding (512-dim float32 array as bytes)', null=True),
        ),
        migrations.AddField(
            model_name='clientuser',
            name='cached_old_photo_embedding',
            field=models.BinaryField(blank=True, help_text='Cached embedding from old profile photo', null=True),
        ),
        migrations.AddField(
            model_name='clientuser',
            name='embedding_cached_at',
            field=models.DateTimeField(blank=True, help_text='When the embedding was last cached', null=True),
        ),
        migrations.AddIndex(
            model_name='clientuser',
            index=models.Index(fields=['embedding_cached_at'], name='clients_cli_embeddi_dcc867_idx'),
        ),
    ]
