# Generated by Django 5.2.7 on 2025-10-08 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdevice',
            name='browser',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
