# Generated by Django 5.2.7 on 2025-10-09 12:43

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import encrypted_model_fields.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_token', models.CharField(db_index=True, max_length=100, unique=True)),
                ('session_type', models.CharField(choices=[('enrollment', 'Enrollment'), ('recognition', 'Recognition'), ('verification', 'Verification'), ('identification', 'Identification')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('expired', 'Expired'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('liveness_required', models.BooleanField(default=False)),
                ('anti_spoofing_required', models.BooleanField(default=False)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('current_attempts', models.PositiveIntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device_fingerprint', models.CharField(blank=True, max_length=255)),
                ('is_successful', models.BooleanField(default=False)),
                ('confidence_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('failure_reason', models.CharField(blank=True, max_length=100)),
                ('frames_processed', models.PositiveIntegerField(default=0)),
                ('processing_time_ms', models.FloatField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_sessions', to='clients.client')),
                ('client_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auth_sessions', to='clients.clientuser')),
            ],
            options={
                'verbose_name': 'Authentication Session',
                'verbose_name_plural': 'Authentication Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FaceEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('embedding_vector', encrypted_model_fields.fields.EncryptedTextField(help_text='Encrypted face embedding vector')),
                ('embedding_dimension', models.PositiveIntegerField(default=512)),
                ('face_quality_score', models.FloatField(help_text='Face image quality score', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('liveness_score', models.FloatField(default=0.0, help_text='Liveness detection score', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('anti_spoofing_score', models.FloatField(default=0.0, help_text='Anti-spoofing detection score', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('face_landmarks', models.JSONField(blank=True, help_text='Facial landmarks coordinates', null=True)),
                ('face_bbox', models.JSONField(blank=True, help_text='Face bounding box coordinates', null=True)),
                ('sample_number', models.PositiveIntegerField(help_text='Sample number in enrollment session')),
                ('total_samples', models.PositiveIntegerField(default=1)),
                ('face_image_path', models.CharField(blank=True, max_length=500)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='clients.client')),
                ('client_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='clients.clientuser')),
                ('enrollment_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='auth_service.authenticationsession')),
            ],
            options={
                'verbose_name': 'Face Enrollment',
                'verbose_name_plural': 'Face Enrollments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FaceRecognitionAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('no_match', 'No Match'), ('multiple_matches', 'Multiple Matches'), ('liveness_failed', 'Liveness Failed'), ('spoofing_detected', 'Spoofing Detected'), ('quality_too_low', 'Quality Too Low')], max_length=20)),
                ('similarity_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('confidence_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('face_quality_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('liveness_score', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('anti_spoofing_score', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('submitted_embedding', encrypted_model_fields.fields.EncryptedTextField(help_text='Encrypted submitted face embedding')),
                ('face_landmarks', models.JSONField(blank=True, null=True)),
                ('face_bbox', models.JSONField(blank=True, null=True)),
                ('processing_time_ms', models.FloatField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device_fingerprint', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recognition_attempts', to='clients.client')),
                ('matched_enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recognition_matches', to='auth_service.faceenrollment')),
                ('matched_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recognition_matches', to='clients.clientuser')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recognition_attempts', to='auth_service.authenticationsession')),
            ],
            options={
                'verbose_name': 'Face Recognition Attempt',
                'verbose_name_plural': 'Face Recognition Attempts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LivenessDetectionResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('live', 'Live Person'), ('spoof', 'Spoof Detected'), ('uncertain', 'Uncertain'), ('error', 'Detection Error')], max_length=20)),
                ('confidence_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('methods_used', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, help_text='Methods used: blink_detection, motion_detection, texture_analysis, etc.', size=None)),
                ('blink_detected', models.BooleanField(default=False)),
                ('motion_detected', models.BooleanField(default=False)),
                ('texture_score', models.FloatField(blank=True, null=True)),
                ('face_movements', models.JSONField(default=list, help_text='Sequence of face movement data')),
                ('frames_analyzed', models.PositiveIntegerField(default=1)),
                ('processing_time_ms', models.FloatField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liveness_results', to='clients.client')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liveness_results', to='auth_service.authenticationsession')),
            ],
            options={
                'verbose_name': 'Liveness Detection Result',
                'verbose_name_plural': 'Liveness Detection Results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_type', models.CharField(choices=[('performance', 'Performance'), ('usage', 'Usage'), ('error', 'Error'), ('security', 'Security')], max_length=20)),
                ('metric_name', models.CharField(db_index=True, max_length=100)),
                ('metric_value', models.FloatField()),
                ('dimensions', models.JSONField(default=dict, help_text='Metric dimensions and tags')),
                ('metadata', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='clients.client')),
            ],
            options={
                'verbose_name': 'System Metric',
                'verbose_name_plural': 'System Metrics',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='authenticationsession',
            index=models.Index(fields=['client', 'session_type'], name='auth_servic_client__017b26_idx'),
        ),
        migrations.AddIndex(
            model_name='authenticationsession',
            index=models.Index(fields=['session_token'], name='auth_servic_session_08aa95_idx'),
        ),
        migrations.AddIndex(
            model_name='authenticationsession',
            index=models.Index(fields=['status', 'expires_at'], name='auth_servic_status_cd98b1_idx'),
        ),
        migrations.AddIndex(
            model_name='authenticationsession',
            index=models.Index(fields=['created_at'], name='auth_servic_created_274f93_idx'),
        ),
        migrations.AddIndex(
            model_name='faceenrollment',
            index=models.Index(fields=['client', 'status'], name='auth_servic_client__cfe90b_idx'),
        ),
        migrations.AddIndex(
            model_name='faceenrollment',
            index=models.Index(fields=['client_user'], name='auth_servic_client__6a4ccc_idx'),
        ),
        migrations.AddIndex(
            model_name='faceenrollment',
            index=models.Index(fields=['created_at'], name='auth_servic_created_b8bdb3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='faceenrollment',
            unique_together={('client_user', 'sample_number')},
        ),
        migrations.AddIndex(
            model_name='facerecognitionattempt',
            index=models.Index(fields=['client', 'result'], name='auth_servic_client__131d25_idx'),
        ),
        migrations.AddIndex(
            model_name='facerecognitionattempt',
            index=models.Index(fields=['session'], name='auth_servic_session_997e9f_idx'),
        ),
        migrations.AddIndex(
            model_name='facerecognitionattempt',
            index=models.Index(fields=['matched_user', 'created_at'], name='auth_servic_matched_6b9aec_idx'),
        ),
        migrations.AddIndex(
            model_name='facerecognitionattempt',
            index=models.Index(fields=['created_at'], name='auth_servic_created_847575_idx'),
        ),
        migrations.AddIndex(
            model_name='livenessdetectionresult',
            index=models.Index(fields=['client', 'status'], name='auth_servic_client__a4782a_idx'),
        ),
        migrations.AddIndex(
            model_name='livenessdetectionresult',
            index=models.Index(fields=['session'], name='auth_servic_session_0e1456_idx'),
        ),
        migrations.AddIndex(
            model_name='livenessdetectionresult',
            index=models.Index(fields=['created_at'], name='auth_servic_created_da072f_idx'),
        ),
        migrations.AddIndex(
            model_name='systemmetrics',
            index=models.Index(fields=['metric_type', 'metric_name'], name='auth_servic_metric__2a3d76_idx'),
        ),
        migrations.AddIndex(
            model_name='systemmetrics',
            index=models.Index(fields=['client', 'timestamp'], name='auth_servic_client__e79b4e_idx'),
        ),
        migrations.AddIndex(
            model_name='systemmetrics',
            index=models.Index(fields=['timestamp'], name='auth_servic_timesta_b44748_idx'),
        ),
    ]
