# Generated by Django 5.2.7 on 2026-01-09 09:22

import auth_service.oidc.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0001_initial'),
        ('clients', '0004_alter_clientuser_old_profile_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faceenrollment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='OAuthClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_id', models.CharField(db_index=True, default=auth_service.oidc.models.generate_client_id, max_length=100, unique=True)),
                ('client_secret', models.CharField(default=auth_service.oidc.models.generate_client_secret, max_length=255)),
                ('name', models.CharField(help_text='Human-readable client name', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('client_type', models.CharField(choices=[('confidential', 'Confidential'), ('public', 'Public')], default='confidential', max_length=20)),
                ('redirect_uris', models.TextField(help_text='Allowed redirect URIs (one per line)')),
                ('grant_types', models.JSONField(default=list, help_text='List of allowed grant types')),
                ('response_types', models.JSONField(default=list, help_text='List of allowed response types (code, token, id_token)')),
                ('allowed_scopes', models.JSONField(default=list, help_text='List of allowed scopes')),
                ('access_token_lifetime', models.PositiveIntegerField(default=3600, help_text='Access token lifetime in seconds')),
                ('refresh_token_lifetime', models.PositiveIntegerField(default=86400, help_text='Refresh token lifetime in seconds')),
                ('id_token_lifetime', models.PositiveIntegerField(default=3600, help_text='ID token lifetime in seconds')),
                ('require_pkce', models.BooleanField(default=True, help_text='Require PKCE for authorization code flow')),
                ('require_consent', models.BooleanField(default=True, help_text='Require user consent before issuing tokens')),
                ('require_face_auth', models.BooleanField(default=True, help_text='Require face authentication for login')),
                ('require_liveness', models.BooleanField(default=True, help_text='Require liveness detection during face auth')),
                ('min_confidence_score', models.FloatField(default=0.85, help_text='Minimum face recognition confidence score')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oauth_clients', to='clients.client')),
            ],
            options={
                'verbose_name': 'OAuth Client',
                'verbose_name_plural': 'OAuth Clients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OAuthToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=255, unique=True)),
                ('token_type', models.CharField(choices=[('access', 'Access Token'), ('refresh', 'Refresh Token')], max_length=10)),
                ('scope', models.CharField(max_length=500)),
                ('is_revoked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='auth_service.oauthclient')),
                ('client_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oauth_tokens', to='clients.clientuser')),
                ('parent_token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_tokens', to='auth_service.oauthtoken')),
            ],
            options={
                'verbose_name': 'OAuth Token',
                'verbose_name_plural': 'OAuth Tokens',
            },
        ),
        migrations.CreateModel(
            name='OIDCSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('face_auth_confidence', models.FloatField(blank=True, null=True)),
                ('liveness_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('access_token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oidc_sessions', to='auth_service.oauthtoken')),
                ('client_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oidc_sessions', to='clients.clientuser')),
            ],
            options={
                'verbose_name': 'OIDC Session',
                'verbose_name_plural': 'OIDC Sessions',
            },
        ),
        migrations.CreateModel(
            name='UserConsent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scopes', models.JSONField(default=list)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_consents', to='auth_service.oauthclient')),
                ('client_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_consents', to='clients.clientuser')),
            ],
            options={
                'verbose_name': 'User Consent',
                'verbose_name_plural': 'User Consents',
            },
        ),
        migrations.CreateModel(
            name='AuthorizationCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=255, unique=True)),
                ('redirect_uri', models.TextField()),
                ('scope', models.CharField(max_length=500)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('nonce', models.CharField(blank=True, max_length=255)),
                ('code_challenge', models.CharField(blank=True, max_length=255)),
                ('code_challenge_method', models.CharField(blank=True, max_length=10)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('auth_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oauth_codes', to='auth_service.authenticationsession')),
                ('client_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_authorization_codes', to='clients.clientuser')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorization_codes', to='auth_service.oauthclient')),
            ],
            options={
                'verbose_name': 'Authorization Code',
                'verbose_name_plural': 'Authorization Codes',
                'indexes': [models.Index(fields=['code'], name='auth_servic_code_7dc4b6_idx'), models.Index(fields=['client', 'expires_at'], name='auth_servic_client__302492_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='oauthtoken',
            index=models.Index(fields=['token'], name='auth_servic_token_2292e4_idx'),
        ),
        migrations.AddIndex(
            model_name='oauthtoken',
            index=models.Index(fields=['client', 'token_type', 'expires_at'], name='auth_servic_client__3c81a1_idx'),
        ),
        migrations.AddIndex(
            model_name='oauthtoken',
            index=models.Index(fields=['client_user', 'token_type'], name='auth_servic_client__87dfdf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userconsent',
            unique_together={('client', 'client_user')},
        ),
    ]
