# Generated by Django 5.2.7 on 2026-01-09 11:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0002_oidc_provider'),
        ('clients', '0004_alter_clientuser_old_profile_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OIDCAuthorizationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('login_identifier', models.CharField(db_index=True, max_length=255)),
                ('redirect_uri', models.TextField()),
                ('scope', models.CharField(max_length=500)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('nonce', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('face_auth_pending', 'Face Auth Pending'), ('face_auth_success', 'Face Auth Success'), ('face_auth_failed', 'Face Auth Failed'), ('consent_granted', 'Consent Granted'), ('consent_denied', 'Consent Denied'), ('code_issued', 'Code Issued'), ('error', 'Error')], default='initiated', max_length=30)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('error_description', models.TextField(blank=True)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('auth_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oauth_logs', to='auth_service.authenticationsession')),
                ('authorization_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='auth_service.authorizationcode')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_logs', to='auth_service.oauthclient')),
                ('client_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oauth_auth_logs', to='clients.clientuser')),
            ],
            options={
                'verbose_name': 'OIDC Authorization Log',
                'verbose_name_plural': 'OIDC Authorization Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', 'created_at'], name='auth_servic_client__edc808_idx'), models.Index(fields=['login_identifier', 'created_at'], name='auth_servic_login_i_5165af_idx'), models.Index(fields=['status', 'created_at'], name='auth_servic_status_5936d4_idx')],
            },
        ),
        migrations.CreateModel(
            name='OIDCTokenLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation', models.CharField(choices=[('issue', 'Issued'), ('refresh', 'Refreshed'), ('revoke', 'Revoked'), ('expire', 'Expired')], max_length=20)),
                ('grant_type', models.CharField(blank=True, max_length=50)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_logs', to='auth_service.oauthclient')),
                ('client_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oauth_token_logs', to='clients.clientuser')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='auth_service.oauthtoken')),
            ],
            options={
                'verbose_name': 'OIDC Token Log',
                'verbose_name_plural': 'OIDC Token Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', 'created_at'], name='auth_servic_client__4bba07_idx'), models.Index(fields=['operation', 'created_at'], name='auth_servic_operati_258e97_idx')],
            },
        ),
    ]
