# Generated by Django 5.2.7 on 2025-10-08 12:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_token', models.CharField(max_length=255, unique=True)),
                ('session_type', models.CharField(choices=[('enrollment', 'Enrollment'), ('authentication', 'Authentication'), ('verification', 'Verification')], max_length=20)),
                ('ice_servers', models.JSONField(default=list)),
                ('constraints', models.JSONField(default=dict)),
                ('peer_connection_id', models.CharField(blank=True, max_length=255)),
                ('remote_address', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.CharField(choices=[('initiating', 'Initiating'), ('connecting', 'Connecting'), ('connected', 'Connected'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('disconnected', 'Disconnected')], default='initiating', max_length=20)),
                ('video_quality', models.CharField(blank=True, max_length=10)),
                ('frame_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('bitrate', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('session_data', models.JSONField(default=dict)),
                ('error_log', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='streaming_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Streaming Session',
                'verbose_name_plural': 'Streaming Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebRTCSignal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('signal_type', models.CharField(choices=[('offer', 'Offer'), ('answer', 'Answer'), ('ice_candidate', 'ICE Candidate'), ('ice_gathering', 'ICE Gathering Complete')], max_length=20)),
                ('signal_data', models.JSONField()),
                ('direction', models.CharField(choices=[('outbound', 'Outbound'), ('inbound', 'Inbound')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='streaming.streamingsession')),
            ],
            options={
                'verbose_name': 'WebRTC Signal',
                'verbose_name_plural': 'WebRTC Signals',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='streamingsession',
            index=models.Index(fields=['session_token'], name='streaming_s_session_e45e47_idx'),
        ),
        migrations.AddIndex(
            model_name='streamingsession',
            index=models.Index(fields=['user', 'created_at'], name='streaming_s_user_id_c85b02_idx'),
        ),
        migrations.AddIndex(
            model_name='streamingsession',
            index=models.Index(fields=['status'], name='streaming_s_status_e7622a_idx'),
        ),
    ]
