# Generated by Django 5.2.7 on 2025-10-08 13:02

import streaming.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamingsession',
            name='session_token',
            field=models.CharField(default=streaming.models.generate_session_token, max_length=255, unique=True),
        ),
    ]
