# Generated by Django 5.2.7 on 2025-10-09 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0002_alter_streamingsession_session_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamingsession',
            name='session_type',
            field=models.CharField(choices=[('enrollment', 'Enrollment'), ('authentication', 'Authentication'), ('verification', 'Verification'), ('identification', 'Identification')], max_length=20),
        ),
    ]
