# Generated by Django 5.2.7 on 2025-10-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_authenticationlog_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticationlog',
            name='attempted_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
