# Generated by Django 5.2.7 on 2025-10-10 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_alter_authenticationlog_attempted_email'),
        ('clients', '0002_add_profile_image_to_clientuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='facerecognitionstats',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='authenticationlog',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Client tenant associated with the authentication attempt', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authentication_logs', to='clients.client'),
        ),
        migrations.AddField(
            model_name='facerecognitionstats',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Client tenant for aggregated recognition statistics', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recognition_stats', to='clients.client'),
        ),
        migrations.AddField(
            model_name='securityalert',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Client tenant that owns this alert', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='security_alerts', to='clients.client'),
        ),
        migrations.AddField(
            model_name='systemmetrics',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Client tenant for the recorded metric', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='system_metrics', to='clients.client'),
        ),
        migrations.AddField(
            model_name='userbehavioranalytics',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Client tenant associated with this behavioral profile', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='behavior_analytics', to='clients.client'),
        ),
        migrations.AlterUniqueTogether(
            name='facerecognitionstats',
            unique_together={('client', 'date', 'hour')},
        ),
        migrations.AddIndex(
            model_name='authenticationlog',
            index=models.Index(fields=['client', 'created_at'], name='analytics_a_client__d07e4e_idx'),
        ),
        migrations.AddIndex(
            model_name='facerecognitionstats',
            index=models.Index(fields=['client', 'date'], name='analytics_f_client__76ea0f_idx'),
        ),
        migrations.AddIndex(
            model_name='securityalert',
            index=models.Index(fields=['client', 'created_at'], name='analytics_s_client__175600_idx'),
        ),
        migrations.AddIndex(
            model_name='systemmetrics',
            index=models.Index(fields=['client', 'timestamp'], name='analytics_s_client__22510a_idx'),
        ),
    ]
