# Generated by Django 5.2.7 on 2025-10-09 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='auditlog',
            name='core_auditl_user_id_413764_idx',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='securityevent',
            name='resolved_by',
        ),
        migrations.RemoveField(
            model_name='securityevent',
            name='user',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.client'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='client_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.clientuser'),
        ),
        migrations.AddField(
            model_name='securityevent',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client'),
        ),
        migrations.AddField(
            model_name='securityevent',
            name='client_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.clientuser'),
        ),
        migrations.AddField(
            model_name='securityevent',
            name='resolved_by_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_security_events', to='clients.client'),
        ),
        migrations.AddField(
            model_name='securityevent',
            name='resolved_by_client_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_security_events_users', to='clients.clientuser'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['client_user', 'created_at'], name='core_auditl_client__692de9_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['client', 'created_at'], name='core_auditl_client__dcdfd3_idx'),
        ),
    ]
